# Generated by Django 4.2.4 on 2023-10-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
